export const ACTION_FETCH_RANDOM = "ACTION_FETCH_RANDOM";

export const GETTER_TODO_LIST = "GETTER_TODO_LIST";
export const GETTER_RANDOM = "GETTER_RANDOM";

export const MUTATE_SET_RANDOM = "MUTATE_SET_RANDOM";
export const MUTATE_ADD_TO_LIST = "MUTATE_ADD_TO_LIST";
export const MUTATE_CLEAR_LIST = "MUTATE_CLEAR_LIST";
export const MUTATE_CLEAR_BY_ID = "MUTATE_CLEAR_BY_ID";

export const PRICE_THRESHOLD = 0.5;
