export const ACTION_FETCH_RANDOM = "ACTION_FETCH_RANDOM";

export const GETTER_TODO_LIST = "GETTER_TODO_LIST";
export const GETTER_RANDOM = "GETTER_RANDOM";

export const MUTATE_SET_TODO_LIST = "MUTATE_SET_TODO_LIST";
export const MUTATE_SET_RANDOM = "MUTATE_SET_RANDOM";
